In [ ]:
import torch
from torch import nn as nn

In [ ]:
model=nn.Sequential(
    nn.Linear(20,256),
    nn.Linear(256,10),
    nn.Linear(10,1)
)
weight_0=model[0].weight
bias_0=model[0].bias
print(weight_0)
print(bias_0)

weight_1=model[1].weight
bias_1=model[1].bias
print(weight_1)
print(bias_1)

Parameter containing:
tensor([[-0.1215, -0.0482, -0.0017,  ..., -0.1140, -0.1982, -0.1362],
        [ 0.1528,  0.1614,  0.0591,  ...,  0.2201, -0.0790, -0.1612],
        [ 0.1348,  0.1688, -0.1258,  ...,  0.0814, -0.1292, -0.1572],
        ...,
        [ 0.1093,  0.1516,  0.0393,  ...,  0.0854,  0.2216, -0.1397],
        [ 0.1925,  0.0187,  0.1702,  ..., -0.1158, -0.1525, -0.0668],
        [-0.1624, -0.0748, -0.1480,  ..., -0.1947, -0.0008, -0.2002]],
       requires_grad=True)
Parameter containing:
tensor([ 0.2057,  0.0080,  0.1341,  0.0036, -0.0523,  0.0428,  0.0684, -0.0112,
        -0.1430, -0.0734, -0.1220, -0.0786, -0.1698,  0.0700, -0.1221,  0.0084,
        -0.0827,  0.0080,  0.0372, -0.2170, -0.2163, -0.0772,  0.1729, -0.0685,
         0.1682,  0.1936, -0.2165, -0.0309,  0.0665,  0.1956,  0.0800,  0.0479,
        -0.0821, -0.0776, -0.1079, -0.1116,  0.0061,  0.1513, -0.0087, -0.0176,
         0.1170,  0.1200,  0.1298,  0.0201,  0.0356,  0.0731, -0.1647,  0.1702,
        -0.1708

In [ ]:
weight0 = model[0].weight
weight1 = model[1].weight
weight2 = model[2].weight

grads0 = model[0].weight.grad
grads1 = model[1].weight.grad
grads2 = model[2].weight.grad

print(grads0)
print(grads1)
print(grads2)


None
None
None


In [ ]:
lr=0.001

weight0 = weight0 - lr *grads0
weight1 = weight1 - lr *grads1
weight2 = weight2 - lr *grads2

TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

In [ ]:
import torch
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [ ]:
features = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
labels = torch.tensor([0, 1, 0])
dataset = TensorDataset(features, labels)
dataloader= DataLoader(dataset, batch_size=2, shuffle=True)
for x,y in dataloader:
  print(x,y)
a,b=dataset[0]
print(a,b)

tensor([[1., 2.],
        [3., 4.]]) tensor([0, 1])
tensor([[5., 6.]]) tensor([0])
tensor([1., 2.]) tensor(0)
