In [ ]:
import torch

In [ ]:
temp=[[2,3,4,5,6,7,8],[2,3,6,8,5,7,2]]
temp1=torch.tensor(temp)
print(temp1)

tensor([[2, 3, 4, 5, 6, 7, 8],
        [2, 3, 6, 8, 5, 7, 2]])


In [ ]:
queue=[[2,3,5,8,5,7,6],[5,7,4,2,43,5,6]]
temp2=torch.tensor(queue)
print(queue)


[[2, 3, 5, 8, 5, 7, 6], [5, 7, 4, 2, 43, 5, 6]]


In [ ]:

print(temp1+temp2)
print(temp1-temp2)
print(temp1*temp2)
print(temp1/temp2)

tensor([[ 4,  6,  9, 13, 11, 14, 14],
        [ 7, 10, 10, 10, 48, 12,  8]])
tensor([[  0,   0,  -1,  -3,   1,   0,   2],
        [ -3,  -4,   2,   6, -38,   2,  -4]])
tensor([[  4,   9,  20,  40,  30,  49,  48],
        [ 10,  21,  24,  16, 215,  35,  12]])
tensor([[1.0000, 1.0000, 0.8000, 0.6250, 1.2000, 1.0000, 1.3333],
        [0.4000, 0.4286, 1.5000, 4.0000, 0.1163, 1.4000, 0.3333]])


In [ ]:
print(temp1.shape)
print(temp2.shape)
print(temp1.dtype)
print(temp2.dtype)
x=temp1+temp2
print(x)
print(x.shape)
print(x.dtype)

torch.Size([2, 7])
torch.Size([2, 7])
torch.int64
torch.int64
tensor([[ 4,  6,  9, 13, 11, 14, 14],
        [ 7, 10, 10, 10, 48, 12,  8]])
torch.Size([2, 7])
torch.int64


In [ ]:
import torch.nn as nn

In [ ]:
inp=torch.tensor([[1.2,2.2,3.2],[4.3,5.3,6.3],[7.8,8.8,9.8]])
print(inp)
print(inp.shape)
print(inp.dtype)

tensor([[1.2000, 2.2000, 3.2000],
        [4.3000, 5.3000, 6.3000],
        [7.8000, 8.8000, 9.8000]])
torch.Size([3, 3])
torch.float32


In [ ]:
linear_layer=nn.Linear(in_features=3,out_features=2)


In [ ]:
output=linear_layer(inp)
print(output)

tensor([[ 0.4020, -2.4564],
        [ 0.8860, -4.4781],
        [ 1.4324, -6.7608]], grad_fn=<AddmmBackward0>)


In [ ]:
model=nn.Sequential(
    nn.Linear(3,9),
    nn.Linear(9,7),
    nn.Linear(7,20),
    nn.Linear(20,5)
)

In [ ]:
output=model(inp)
print(output)


tensor([[-0.0463,  0.1956,  0.3651,  0.0264,  0.2152],
        [-0.0286, -0.0279,  0.8395,  0.5626,  0.6022],
        [-0.0085, -0.2802,  1.3750,  1.1680,  1.0391]],
       grad_fn=<AddmmBackward0>)


In [ ]:
inp=torch.tensor([[1.2,2.2,3.2],[4.3,5.3,6.3],[7.8,8.8,9.8]])

sigmoid=nn.Sigmoid()
output=sigmoid(inp)
print(output)

tensor([[0.7685, 0.9002, 0.9608],
        [0.9866, 0.9950, 0.9982],
        [0.9996, 0.9998, 0.9999]])


In [ ]:
inp=torch.tensor([[1.2,2.2,3.2],[4.3,5.3,6.3],[7.8,8.8,9.8]])

model=nn.Sequential(
    nn.Linear(3,9),
    nn.Linear(9,7),
    nn.Linear(7,20),
    nn.Linear(20,5),
    nn.Sigmoid()
)
output=model(inp)
print(output)

tensor([[0.5195, 0.4818, 0.4493, 0.4765, 0.5810],
        [0.5375, 0.4594, 0.4463, 0.4962, 0.6112],
        [0.5577, 0.4343, 0.4430, 0.5184, 0.6444]], grad_fn=<SigmoidBackward0>)


In [ ]:
inp=torch.tensor([[1.2,2.2,3.2],[4.3,5.3,6.3],[7.8,8.8,9.8]])
probabilities= nn.Softmax(dim=-1)
output=probabilities(inp)
print(output)

tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])


In [ ]:
inp=torch.tensor([[1.2,2.2,3.2],[4.3,5.3,6.3],[7.8,8.8,9.8]])

model=nn.Sequential(
    nn.Linear(3,9),
    nn.Linear(9,7),
    nn.Linear(7,20),
    nn.Linear(20,5),
    nn.Softmax(dim=-1)
)
output=model(inp)
print(output)

tensor([[0.1221, 0.1915, 0.3903, 0.1475, 0.1486],
        [0.0812, 0.1971, 0.5278, 0.0955, 0.0984],
        [0.0458, 0.1822, 0.6643, 0.0524, 0.0553]], grad_fn=<SoftmaxBackward0>)


In [ ]:
import torch.nn.functional as F

In [ ]:
print(F.one_hot(torch.tensor(0),num_classes=5))
print(F.one_hot(torch.tensor(0),num_classes=5).shape)

tensor([1, 0, 0, 0, 0])
torch.Size([5])
